spring:
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          fetch_size: 50
        order_inserts: true
        order_updates: true
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/postgres?reWriteBatchedInserts=true
    username: postgres
    password:
---
spring:
  config:
    activate:
      on-profile: "test"
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/postgres?reWriteBatchedInserts=true
    username: postgres
    password: