include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

variables:
  NEXUS_URL: "$NEXUS_URL"
  NEXUS_USER: "$NEXUS_USER"
  NEXUS_PASS: "$NEXUS_PASS"
  COMMIT_TAG: "$CI_COMMIT_SHORT_SHA"

stages:
  - test
  - build
  - infrastructure
  - acceptance

application test:
  stage: test
  image: gradle:jdk17-focal
  variables:
    GIT_DEPTH: "0"
  script:
    - cd backend/application
    - gradle clean test
  artifacts:
    when: always
    reports:
      junit:
        - backend/application/build/test-results/test/**/TEST-*.xml

adapter tests:
  stage: test
  image: gradle:jdk17-focal
  variables:
    GIT_DEPTH: "0"
  script:
    - cd backend/adapters
    - gradle clean test
  artifacts:
    when: always
    reports:
      junit:
        - backend/adapters/build/test-results/test/**/TEST-*.xml

build and push:
  only:
    - master
  stage: build
  script:
    - docker login -u ${NEXUS_USER} -p ${NEXUS_PASS} ${NEXUS_URL}
    - docker compose build
    - docker compose push
    - docker logout ${NEXUS_URL}

deploy to stage:
  allow_failure: false
  timeout: 15m
  only:
    - master
  environment: stage
  resource_group: stage
  stage: infrastructure
  script:
    - !reference [ .ansible-deploy ]

api tests:
  only:
    - master
  stage: acceptance

prepare data:
  needs:
    - api tests
  only:
    - master
  stage: acceptance

ui tests:
  needs:
    - prepare data
  only:
    - master
  stage: acceptance
