image: openjdk:17-alpine

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

stages:
  - test

application test:
  only:
    - main
  stage: test
  image: gradle:jdk17-focal
  variables:
    GIT_DEPTH: "0"
  script:
    - cd backend/application
    - gradle clean test
  artifacts:
    when: always
    reports:
      junit:
        - backend/application/build/test-results/test/**/TEST-*.xml

adapter tests:
  needs: []
  only:
    - main
  stage: test
  image: gradle:jdk17-focal
  variables:
    GIT_DEPTH: "0"
  script:
    - cd backend/adapters
    - gradle clean test
  artifacts:
    when: always
    reports:
      junit:
        - backend/adapters/build/test-results/test/**/TEST-*.xml