include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - '/infra/gitlab/ansible-deploy.yaml'

variables:
  NEXUS_URL: "$NEXUS_URL"
  NEXUS_USER: "$NEXUS_USER"
  NEXUS_PASS: "$NEXUS_PASS"
  COMMIT_TAG: "11f4cb46"
  ANSIBLE_SSH_KEY: "$ANSIBLE_SSH_KEY"

stages:
  - test
  - build
  - infrastructure
  - acceptance

deploy to stage:
  allow_failure: false
  timeout: 15m
  image: '$NEXUS_URL/ioque/ansible'
  only:
    - master
  environment: stage
  resource_group: stage
  stage: infrastructure
  script:
    - mkdir ${CI_PROJECT_DIR}/secret
    - echo "$ANSIBLE_SSH_KEY" > ${CI_PROJECT_DIR}/secret/ansible.key
    - chmod 400 ${CI_PROJECT_DIR}/secret/ansible.key
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - export ANSIBLE_CONFIG=${CI_PROJECT_DIR}/infra/ansible/ansible.cfg
    - cd ${CI_PROJECT_DIR}/infra/ansible
    - ansible-playbook --private-key ${CI_PROJECT_DIR}/secret/ansible.key --user linux playbooks/deploy.yml -l "${CI_ENVIRONMENT_NAME}"
