entry-pipeline:
  delay: "100"
  source:
    otel_trace_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline"
entry-pipeline-metrics:
  delay: "100"
  source:
    otel_metrics_source:
      ssl: false
  sink:
    - pipeline:
        name: "raw-pipeline-metrics"
raw-pipeline:
  source:
    pipeline:
      name: "entry-pipeline"
  processor:
    - otel_trace_raw:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: admin
        password: admin
        index_type: trace-analytics-raw

raw-pipeline-metrics:
  source:
    pipeline:
      name: "entry-pipeline-metrics"
  processor:
    - otel_metrics_raw_processor:
  sink:
    - opensearch:
        hosts: [ "http://opensearch:9200" ]
        username: admin
        password: admin
        index: "metrics"