- name: Copy docker-compose file
  copy:
    src: ../../../../docker-compose.yml
    dest: ~/investment-fund/
    owner: root
    group: root
    mode: '0644'

- name: Start
  shell: |
    export BACKEND_DB_HOST={{ lookup('ansible.builtin.env', 'BACKEND_DB_HOST') }} 
    export BACKEND_ENV={{ lookup('ansible.builtin.env', 'BACKEND_ENV') }} 
    export FRONTEND_API_HOST={{ lookup('ansible.builtin.env', 'FRONTEND_API_HOST') }} 
    export FRONTEND_API_HTTP_MODE={{ lookup('ansible.builtin.env', 'FRONTEND_API_HTTP_MODE') }} 
    export COMMIT_TAG={{ lookup('ansible.builtin.env', 'COMMIT_TAG') }} 
    docker compose down -v --rmi all
    docker compose up --wait
    exit 0
  args:
    chdir: ~/investment-fund
