.ansible-deploy:
  - |
    export ANSIBLE_HOST_KEY_CHECKING=False
    export ANSIBLE_CONFIG=${CI_PROJECT_DIR}/infra/ansible/ansible.cfg
    cd ${CI_PROJECT_DIR}/infra/ansible
    ansible-playbook -v playbooks/deploy.yml -l "${CI_ENVIRONMENT_NAME}" --private-key ${CI_PROJECT_DIR}/secret/ansible.key