.ansible-deploy:
  - |
    export ANSIBLE_CONFIG=infra/ansible/ansible.cfg
    cd infra/ansible
    ansible-playbook --private-key secret/ansible.key --user linux playbooks/deploy.yml -l "${CI_ENVIRONMENT_NAME}"