.ansible-deploy:
  - |
    export ANSIBLE_CONFIG=${CI_PROJECT_DIR}/infra/ansible/ansible.cfg
    cd ${CI_PROJECT_DIR}/infra/ansible
    ansible-playbook playbooks/deploy.yml --vault-pass-file=/root/ansible-vault.key -l "${CI_ENVIRONMENT_NAME}"