version: "3.9"
services:
  signal-scanner-db:
    container_name: signal-scanner-db
    build:
      context: postgres
    ports:
      - "54321:5432"
    volumes:
      - signal-scanner-db:/var/lib/postgresql/data
  signal-scanner-test-db:
    container_name: signal-scanner-test-db
    build:
      context: postgres
    ports:
      - "54322:5432"
    volumes:
      - signal-scanner-test-db:/var/lib/postgresql/data
volumes:
  signal-scanner-db:
    driver: local
  signal-scanner-test-db:
    driver: local