version: "3.9"
services:
  signal-scanner-db:
    container_name: signal-scanner-db
    image: 192.168.0.62:8002/ioque/postgres:${COMMIT_TAG:-latest}
    ports:
      - "5432:5432"
    volumes:
      - signal-scanner-db:/var/lib/pgpro/std-15/data

  backend:
    container_name: backend
    image: 192.168.0.62:8002/ioque/backend:${COMMIT_TAG:-latest}
    ports:
      - "8080:8080"
    environment:
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      KAFKA_HOST: ${MACHINE_HOST}
      ROOT_LOG_LEVEL: ${ROOT_LOG_LEVEL:-DEBUG}
      DB_HOST: ${MACHINE_HOST}
      DB_PORT: "5432"
      SPRING_PROFILES_ACTIVE: ${BACKEND_ENV:-prod}
    healthcheck:
      test: wget --no-verbose --tries=1 --spider  http://localhost:8080/actuator/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    depends_on:
      signal-scanner-db:
        condition: service_started
      kafka:
        condition: service_healthy

  frontend:
    container_name: frontend
    image: 192.168.0.62:8002/ioque/frontend:${COMMIT_TAG:-latest}
    environment:
      API_HOST: ${MACHINE_HOST}
      API_HTTP_MODE: ${API_HTTP_MODE}
    ports:
      - "4200:4200"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider  http://localhost:4200/ || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s

  datasource:
    container_name: datasource
    image: 192.168.0.62:8002/ioque/datasource:${COMMIT_TAG:-latest}
    ports:
      - "8081:8081"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider  http://localhost:8081/actuator/health || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.4.1
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://${MACHINE_HOST}:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
    healthcheck:
      test: nc -z localhost 9092 || exit -1
      start_period: 15s
      interval: 5s
      timeout: 10s
      retries: 10
    depends_on:
      - zookeeper

  kafka-init-topics:
    image: confluentinc/cp-kafka:7.4.1
    entrypoint: [ '/bin/sh', '-c' ]
    depends_on:
      - kafka
    command: |
      "
      kafka-topics --bootstrap-server kafka:29092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic commands --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic events --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic signal-scanner-business-log --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic signal-scanner-technical-log --replication-factor 1 --partitions 1

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "

  kafbat-ui:
    container_name: kafbat-ui
    image: ghcr.io/kafbat/kafka-ui:latest
    ports:
      - "8085:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      KAFKA_CLUSTERS_0_AUDIT_TOPICAUDITENABLED: 'true'
      KAFKA_CLUSTERS_0_AUDIT_CONSOLEAUDITENABLED: 'true'
    depends_on:
      - kafka

  elasticsearch:
    image: elasticsearch:7.14.2
    volumes:
      - elasticsearch:/var/lib/elasticsearch/data
    environment:
      ES_JAVA_OPTS: "-Xmx512m -Xms256m"
      ELASTIC_PASSWORD: elastic
      discovery.type: single-node
      xpack.security.enabled: "true"
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped

  kibana:
    image: kibana:7.14.2
    environment:
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: elastic
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: "true"
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - logstash

  logstash:
    image: 192.168.0.62:8002/ioque/logstash:${COMMIT_TAG:-latest}
    container_name: logstash
    ports:
      - "5044:5044"
      - "5046:5046"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
#  moex-datasource:
#    container_name: moex-datasource
#    build:
#      context: moex-datasource
#    image: 192.168.0.62:8002/ioque/moex-datasource:${COMMIT_TAG:-latest}
#    ports:
#      - "8082:8081"
#    healthcheck:
#      test: wget --no-verbose --tries=1 --spider  http://localhost:8081/actuator/health || exit 1
#      interval: 5s
#      retries: 5
#      start_period: 20s
#      timeout: 10s

volumes:
  elasticsearch:
    driver: local
  signal-scanner-db:
    driver: local