---
- name: deploy application
  hosts:
    - stage
    - manual
  gather_facts: false
  become: true
  vars_files:
    - "../environments/group_vars/docker-configure-docker-host.yml"
  roles:
    - all-system-wait-connection
    - all-system-reboot
    - docker-configure-docker-host
    - docker-compose-up