---
- name: deploy application
  hosts:
    - test
  gather_facts: false
  become: true
  roles:
    - all-system-wait-connection
    - all-system-reboot
    - docker-configure-docker-host
    - docker-compose-up